spring:
  application:
    name: hubble
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hubble_db?schema=hubble_db
    username: postgres
    password: root
    pool:
      initial-size: 10
      max-size: 10
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: jheann.elec@gmail.com
    password: ${MAIL_APP_PASSWORD:mygvybqakkeiwquc}
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: false
      mail.smtp.connectiontimeout: 15000
      mail.smtp.timeout: 15000
      mail.smtp.writetimeout: 15000

server:
  port: 8090

hubble:
  jwt:
    rsa-private-key-path: classpath:jwt/private.pem
    rsa-public-key-path: classpath:jwt/public.pem
    access-minutes: 15
    refresh-days: 30
  app:
    password-reset-validity-minutes: 3
    storage-path: D:\storage
    max-avatar-size-bytes: 5242880

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
